# Generated by Django 4.0 on 2021-12-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_data', models.FloatField(verbose_name='Valor')),
            ],
            options={
                'verbose_name_plural': 'Mediciones',
            },
        ),
    ]
